# ==============================================
# PureNodes | Surfboard 专用节点列表
# 自动更新：GitHub Actions
# ==============================================

[Proxy]
[anytls]🇨🇳TW台湾 anytls 01 x1 = anytls, 1.6rguyesfdhvbz.uk, 443, b1707d5c-72e9-4147-ab45-d3b0419d6f98, udp-relay=true, sni=false
[anytls]🇨🇳TW台湾 anytls 02 x1 = anytls, 2.6rguyesfdhvbz.uk, 443, b1707d5c-72e9-4147-ab45-d3b0419d6f98, udp-relay=true, sni=false
[anytls]🇩🇪DE德国 anytls 01 x1 = anytls, 1.6rguyesfdhvbz.uk, 443, b1707d5c-72e9-4147-ab45-d3b0419d6f98, udp-relay=true, sni=false
[anytls]🇭🇰HK香港 anytls 01 x1 = anytls, 1.6rguyesfdhvbz.uk, 443, b1707d5c-72e9-4147-ab45-d3b0419d6f98, udp-relay=true, sni=false
[anytls]🇭🇰HK香港 anytls 02 x1 = anytls, 2.6rguyesfdhvbz.uk, 443, b1707d5c-72e9-4147-ab45-d3b0419d6f98, udp-relay=true, sni=false
[anytls]🇭🇰HK香港 anytls 03 x1 = anytls, 1.6rguyesfdhvbz.uk, 443, b1707d5c-72e9-4147-ab45-d3b0419d6f98, udp-relay=true, sni=false
[anytls]🇭🇰HK香港 anytls 04 x1 = anytls, 2.6rguyesfdhvbz.uk, 443, b1707d5c-72e9-4147-ab45-d3b0419d6f98, udp-relay=true, sni=false
[anytls]🇮🇳IN印度 anytls 01 x1 = anytls, 2.6rguyesfdhvbz.uk, 443, b1707d5c-72e9-4147-ab45-d3b0419d6f98, udp-relay=true, sni=false
[anytls]🇯🇵JP日本 anytls 01 x1 = anytls, 2.6rguyesfdhvbz.uk, 443, b1707d5c-72e9-4147-ab45-d3b0419d6f98, udp-relay=true, sni=false
[anytls]🇯🇵JP日本 anytls 02 x1 = anytls, 2.6rguyesfdhvbz.uk, 443, b1707d5c-72e9-4147-ab45-d3b0419d6f98, udp-relay=true, sni=false
[anytls]🇯🇵JP日本 anytls 03 x1 = anytls, 2.6rguyesfdhvbz.uk, 443, b1707d5c-72e9-4147-ab45-d3b0419d6f98, udp-relay=true, sni=false
[anytls]🇳🇬NG尼日利亚 anytls 01 x1 = anytls, 1.6rguyesfdhvbz.uk, 443, b1707d5c-72e9-4147-ab45-d3b0419d6f98, udp-relay=true, sni=false
[anytls]🇸🇬SG新加坡 anytls 01 x1 = anytls, 1.6rguyesfdhvbz.uk, 443, b1707d5c-72e9-4147-ab45-d3b0419d6f98, udp-relay=true, sni=false
[anytls]🇸🇬SG新加坡 anytls 02 x1 = anytls, 1.6rguyesfdhvbz.uk, 443, b1707d5c-72e9-4147-ab45-d3b0419d6f98, udp-relay=true, sni=false
[anytls]🇸🇬SG新加坡 anytls 03 x1 = anytls, 1.6rguyesfdhvbz.uk, 443, b1707d5c-72e9-4147-ab45-d3b0419d6f98, udp-relay=true, sni=false
